### PR TITLE
Fix regression mailer preview path

### LINKED ISSUE #1386: Rails 3.2.1 does not start with rspec-rails 3.2.2
It should be a consequence of #1327, as per https://github.com/rspec/rspec-rails/pull/1327#issuecomment-108278230

```sh
$ rails c
~/.rvm/gems/ruby-2.1.5/gems/actionmailer-3.2.21/lib/action_mailer/base.rb:438:in `method_missing': undefined method `preview_path=' for ActionMailer::Base:Class (NoMethodError)
```

### PR DESCRIPTION
**Pull request by cupakromer**
This fixes the regression where setting the `ActionMailer` preview path leaked into versions which does not support it (Rails before 4.1).

The cause of the regression was a series of failures:

- The integration spec did not force `ActionMailer::Base` to load; thus the incorrect setting was not loaded exposing the issue
- In the case of older Rails versions, it was believed that the mailer spec's script defaulting to the "development" environment would be sufficient. However, when shelling out the existing Ruby `ENV` was already available, resulting in the `RAILS_ENV` already being set to "test". Thus the test was not explicitly testing the code as expected.
- The implementation code itself made a note about `config.action_mailer.show_previews` always returning `true`, yet code slightly further down was relying on `config.action_mailer.preview_path` being able to return `false` (which it never will)

This fixes each of these issues.

Based on minimal local testing it appears that `defined?(ActionMailer)`, while possibly loading `ActionMailer`, will _not_ force the configuration to load. The configuration is only with `ActionMailer::Base`.

I'm weary :weary: about switching out the logic yet again regarding: `defined?(ActionMailer)` vs `config.respond_to?(:action_mailer)`. It's possible that on any further version the behavior of the config being loaded or the config changing to always respond `true` can occur. For now, it seems that `config.respond_to?(:action_mailer)` is working and stable. Though I'm always open to further discussion.

Resolve #1386

/cc @tagliala, @olance, @myronmarston

### CODE REVIEW

File: example_app_generator/generate_action_mailer_specs.rb [hunk 1]
```diff
@@ -14,11 +14,25 @@ def comment_lines(path, flag, *args)
...
+      else
+        Rails.application.configure do
+          config.action_mailer.default_url_options = { :host => ENV['DEFAULT_URL'] }
+        end
       end
     end
+
+    if defined?(ActionMailer)
+      # This will force the loading of ActionMailer settings
+      ActionMailer::Base.smtp_settings
```
Comment (JonRowe) [inline example_app_generator/generate_action_mailer_specs.rb]: Is the same on all versions of Rails?

File: lib/rspec-rails.rb [hunk 2]
```diff
@@ -59,8 +52,18 @@ def config_default_preview_path(options)
...
+        # respond.
+        #
+        # This string version check avoids loading the ActionMailer class, as
+        # would happen using `defined?`. This is necessary because the
+        # ActionMailer class only loads it's settings once, at load time. If we
+        # load the class now any settings declared in a config block in an
+        # initializer will be ignored.
+        #
+        # We cannot use `config.action_mailer.respond_to?(:preview_path)` here
+        # as it will always return `true`.
```
Comment (JonRowe) [inline lib/rspec-rails.rb]: Rails is a ghetto

File: example_app_generator/generate_action_mailer_specs.rb (hunk 1 above)
Comment (cupakromer) [inline example_app_generator/generate_action_mailer_specs.rb]: From what I can tell.

File: example_app_generator/generate_action_mailer_specs.rb [hunk 3]
```diff
@@ -14,11 +14,25 @@ def comment_lines(path, flag, *args)
...
-      Rails.application.configure do
-        config.action_mailer.default_url_options = { :host => ENV['DEFAULT_URL'] }
+      if ::Rails::VERSION::STRING < '4.1'
+        ExampleApp::Application.configure do
+          config.action_mailer.default_url_options = { :host => ENV['DEFAULT_URL'] }
+        end
+      else
+        Rails.application.configure do
+          config.action_mailer.default_url_options = { :host => ENV['DEFAULT_URL'] }
+        end
```
Comment (JonRowe) [inline example_app_generator/generate_action_mailer_specs.rb]: Just curious why this change is related to this PR? Shouldn't we always have been doing this?

Comment (cupakromer) [inline example_app_generator/generate_action_mailer_specs.rb]: Yes, it should always have been there. Rails changed how they provided access to the configuration in 4.1. Incidentally the mailer specs / script never executed with a code path testing a default url option on Rails < 4.1. Which is also partially related to why this issue wasn't noticed sooner.

After fixing the mailer specs to run better coverage for Rails < 4.1, reproducing the issue, more things started failing as this code path was actually run. Thus, a fix is included here. The commit 9522842 has a long explanation of several related things which got fixed in the spec suite.

**Comment by myronmarston** [comment]
Thanks for getting on this promptly, @cupakromer.  I'm happy to defer to @JonRowe's review since I don't really have the context for this.

**Comment by JonRowe** [comment]
Looks all good to me

**Comment by olance** [comment]
:+1:

**Comment by myronmarston** [comment]
@cupakromer Are you planning to work up a 3-2-maintenance backport for this?

**Comment by cupakromer** [comment]
@myronmarston done: #1389

Just waiting for the sanity check to go green.

**Comment by chrisbloom7** [comment]
FYI Currently blocked on upgrading a Rails 4.0 app to use Ruby 2.2. This bug is preventing me from upgrading to rspec-rails 3.2, but issue #1273 prevents the suite from running on rspec-rails 3.1 (recommended solution: upgrade to 3.2)

**Comment by myronmarston** [comment]
@chrisbloom7 -- I released rspec-rails 3.2.3 with a fix for this yesterday, so you should be able to upgrade now.

**Comment by chrisbloom7** [comment]
@myronmarston Thanks, everything is green on Rails 4.0, rspec-rails 3.2.2, and Ruby 2.2.2
